stages:
 - test
 - coverage

test_latest:
  image: rocker/r-base
  stage: test
  script:
  - r -e 'install.packages(c("data.table", "testthat", "RcppRoll", "knitr", "rmarkdown"))'
  - R CMD build . --no-manual --no-build-vignettes
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - R CMD check "${PKG_FILE_NAME}" --no-manual --no-build-vignettes
  only:
  - master

coverage_job:
  image: rocker/r-base
  stage: coverage
  when: on_success
  only:
    - master
  script:
    - r -e 'install.packages("covr", "devtools")'
    - r -e 'devtools::install()'
    - r -e 'covr::codecov(type = c("tests", "examples"), quiet = FALSE, token = "49da8c07-70b6-46ee-a2e2-f1d1d5784a9a")'
